# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='avatar/default.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='\u7528\u6237\u5934\u50cf')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u6e38\u5ba2',
                'verbose_name_plural': '\u6e38\u5ba2',
            },
        ),
    ]
