# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5bc6\u7801'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
