# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0003_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5bc6\u7801'),
        ),
    ]
